export const quest = [
  { name: 'Array', total: 25, link: 'array' },
  { name: 'Dynamic Programming', total: 80, link: 'dp' },
  { name: 'Matrix', total: 80, link: 'matrix' },
  { name: 'String', total: 80, link: 'string' },
  { name: 'Searching & Sorting', total: 80, link: 'searchingsorting' },
  { name: 'Linkedlist', total: 80, link: 'linkedlist' },
  { name: 'Binary Trees', total: 80, link: 'binarytrees' },
  { name: 'Binary Search Trees', total: 80, link: 'binarysearchtrees' },
  { name: 'Greedy Algorithm', total: 80, link: 'greedyalgorithm' },
  { name: 'Backtracking', total: 80, link: 'backtracking' },
  { name: 'Stacks & Queues', total: 80, link: 'stackandqueues' },
  { name: 'Heap', total: 80, link: 'heap' },
  { name: 'Graph', total: 80, link: 'graph' },
  { name: 'Trie', total: 80, link: 'trie' },
  { name: 'Bit Manipulation', total: 80, link: 'bitmanipulation' },
];
